"""Not a check itself — lesson-generation constants and configuration.

Single settings surface for the lesson-generation workflow: the batch,
promotion, and checkpointable package-graph layers. All constants use
``K_LESSON_GENERATION_<NAME>`` upper snake case; no other module in this
package defines module-level configuration constants.

The ``catalog_generation`` scratch directory, checkpoint DB name, thread-id
prefix, and plan/approval schema strings keep their historical values so
existing runs, checkpoints, and batch aggregates remain resumable and
compatible.
"""

from __future__ import annotations

from pathlib import Path

# ── Batch, promotion, and plan-compatibility paths ──────────────────────

K_LESSON_GENERATION_SCRATCH_ROOT = Path("store") / "scratch" / "catalog_generation"
K_LESSON_GENERATION_APPROVAL_SCHEMA = "1"
K_LESSON_GENERATION_DEFAULT_WORKERS = 6
K_LESSON_GENERATION_RUN_ID_MAX_LENGTH = 64
K_LESSON_GENERATION_DEFAULT_JOB = "author"
K_LESSON_GENERATION_PLAN_SCHEMA = "0.5-catalog-plan"
K_LESSON_GENERATION_PLAN_SCHEMAS = frozenset(
    {
        K_LESSON_GENERATION_PLAN_SCHEMA,
        "0.4-catalog-plan",
        "0.3-catalog-plan",
        "0.2-catalog-plan",
        "0.1-catalog-plan",
    }
)

# ── Source package files ─────────────────────────────────────────────────

K_LESSON_GENERATION_PLAN_FILE = "plan.md"
K_LESSON_GENERATION_LESSON_FILE = "lesson.md"
K_LESSON_GENERATION_EXERCISES_FILE = "exercises.yaml"
K_LESSON_GENERATION_TRANSCRIPT_FILE = "transcript.yaml"
K_LESSON_GENERATION_EXERCISE_DIAGNOSTICS_FILE = "exercise_diagnostics.json"

K_LESSON_GENERATION_AUTHORING_FILES: tuple[str, ...] = (
    K_LESSON_GENERATION_PLAN_FILE,
    K_LESSON_GENERATION_LESSON_FILE,
    K_LESSON_GENERATION_EXERCISES_FILE,
)
K_LESSON_GENERATION_DERIVED_FILES: tuple[str, ...] = (K_LESSON_GENERATION_TRANSCRIPT_FILE,)
K_LESSON_GENERATION_REQUIRED_FILES = K_LESSON_GENERATION_AUTHORING_FILES
K_LESSON_GENERATION_SOURCE_FILES: tuple[str, ...] = (
    *K_LESSON_GENERATION_AUTHORING_FILES,
    *K_LESSON_GENERATION_DERIVED_FILES,
)

# ── Output layout ────────────────────────────────────────────────────────

K_LESSON_GENERATION_SOURCE_SUBDIR = "source"
K_LESSON_GENERATION_QUALITY_REVIEW_JOB = "reviewer"
K_LESSON_GENERATION_REVIEW_EDIT_SUBDIR = "review_edit"
K_LESSON_GENERATION_REVIEW_EDIT_JOB = "reviewer"
K_LESSON_GENERATION_REVIEW_EDIT_MAX_REASKS = 1
K_LESSON_GENERATION_EXPORT_SUBDIR = "export"
K_LESSON_GENERATION_CHECKPOINTS_FILE = "catalog_generation_checkpoints.db"
K_LESSON_GENERATION_LEDGER_FILE = "acceptance_ledger.jsonl"

# ── Schedule ─────────────────────────────────────────────────────────────

K_LESSON_GENERATION_COURSE_ID = "nb-course-catalog-generation"
K_LESSON_GENERATION_ALLOWED_KINDS: tuple[str, ...] = (
    "grammar",
    "communicative",
    "pronunciation",
    "phraseology",
    "writing",
)
K_LESSON_GENERATION_SCHEMA_VERSION = "0.1-catalog-package"
K_LESSON_GENERATION_SCHEDULE_SLOT_MODULUS = 10000
K_LESSON_GENERATION_NORMALIZER_JOB = "normalizer"
K_LESSON_GENERATION_EXERCISE_AUTHOR_JOB = "exercise_author"

# ── Hashing ──────────────────────────────────────────────────────────────

K_LESSON_GENERATION_HASH_ALGO = "sha256"
K_LESSON_GENERATION_HASH_PREFIX = "sha256:"

# ── Lifecycle stages ─────────────────────────────────────────────────────

K_LESSON_GENERATION_STAGE_PREPARING = "preparing"
K_LESSON_GENERATION_STAGE_PARKED = "parked"
K_LESSON_GENERATION_STAGE_COMPLETE = "complete"
K_LESSON_GENERATION_STAGE_ACCEPTED = "accepted"
K_LESSON_GENERATION_STAGE_DEFERRED = "deferred"
K_LESSON_GENERATION_STAGE_REJECTED = "rejected"

# ── Human decisions ──────────────────────────────────────────────────────

K_LESSON_GENERATION_DECISION_ACCEPT = "accept"
K_LESSON_GENERATION_DECISION_DEFER = "defer"
K_LESSON_GENERATION_DECISION_REJECT = "reject"
K_LESSON_GENERATION_DECISIONS: tuple[str, ...] = (
    K_LESSON_GENERATION_DECISION_ACCEPT,
    K_LESSON_GENERATION_DECISION_DEFER,
    K_LESSON_GENERATION_DECISION_REJECT,
)

K_LESSON_GENERATION_DEFAULT_REVIEWER = "catalog-package-operator"

# ── Graph node names ─────────────────────────────────────────────────────

K_LESSON_GENERATION_NODE_PREPARE = "prepare"
K_LESSON_GENERATION_NODE_AUTHOR = "author"
K_LESSON_GENERATION_NODE_REVIEW = "review"
K_LESSON_GENERATION_NODE_NORMALIZE = "normalize"
K_LESSON_GENERATION_NODE_PRESERVATION = "preservation"
K_LESSON_GENERATION_NODE_INTENT_REVIEW = "intent_review"
K_LESSON_GENERATION_NODE_EXERCISE_AUTHOR = "exercise_author"
K_LESSON_GENERATION_NODE_EXERCISE_COMPILE = "exercise_compile"
K_LESSON_GENERATION_NODE_EXERCISE_VERIFY = "exercise_verify"
K_LESSON_GENERATION_NODE_COVERAGE = "coverage"
K_LESSON_GENERATION_NODE_VERIFY_ATTESTATIONS = "verify_attestations"
K_LESSON_GENERATION_NODE_HUMAN_GATE = "human_gate"
K_LESSON_GENERATION_NODE_FINALIZE = "finalize"

# ── Export ───────────────────────────────────────────────────────────────

K_LESSON_GENERATION_EXPORT_INDENT = 2

__all__ = [
    "K_LESSON_GENERATION_SCRATCH_ROOT",
    "K_LESSON_GENERATION_APPROVAL_SCHEMA",
    "K_LESSON_GENERATION_DEFAULT_WORKERS",
    "K_LESSON_GENERATION_RUN_ID_MAX_LENGTH",
    "K_LESSON_GENERATION_DEFAULT_JOB",
    "K_LESSON_GENERATION_PLAN_SCHEMA",
    "K_LESSON_GENERATION_PLAN_SCHEMAS",
    "K_LESSON_GENERATION_PLAN_FILE",
    "K_LESSON_GENERATION_LESSON_FILE",
    "K_LESSON_GENERATION_EXERCISES_FILE",
    "K_LESSON_GENERATION_TRANSCRIPT_FILE",
    "K_LESSON_GENERATION_EXERCISE_DIAGNOSTICS_FILE",
    "K_LESSON_GENERATION_AUTHORING_FILES",
    "K_LESSON_GENERATION_DERIVED_FILES",
    "K_LESSON_GENERATION_REQUIRED_FILES",
    "K_LESSON_GENERATION_SOURCE_FILES",
    "K_LESSON_GENERATION_SOURCE_SUBDIR",
    "K_LESSON_GENERATION_QUALITY_REVIEW_JOB",
    "K_LESSON_GENERATION_EXPORT_SUBDIR",
    "K_LESSON_GENERATION_CHECKPOINTS_FILE",
    "K_LESSON_GENERATION_LEDGER_FILE",
    "K_LESSON_GENERATION_COURSE_ID",
    "K_LESSON_GENERATION_ALLOWED_KINDS",
    "K_LESSON_GENERATION_SCHEMA_VERSION",
    "K_LESSON_GENERATION_SCHEDULE_SLOT_MODULUS",
    "K_LESSON_GENERATION_NORMALIZER_JOB",
    "K_LESSON_GENERATION_EXERCISE_AUTHOR_JOB",
    "K_LESSON_GENERATION_HASH_ALGO",
    "K_LESSON_GENERATION_HASH_PREFIX",
    "K_LESSON_GENERATION_STAGE_PREPARING",
    "K_LESSON_GENERATION_STAGE_PARKED",
    "K_LESSON_GENERATION_STAGE_COMPLETE",
    "K_LESSON_GENERATION_STAGE_ACCEPTED",
    "K_LESSON_GENERATION_STAGE_DEFERRED",
    "K_LESSON_GENERATION_STAGE_REJECTED",
    "K_LESSON_GENERATION_DECISION_ACCEPT",
    "K_LESSON_GENERATION_DECISION_DEFER",
    "K_LESSON_GENERATION_DECISION_REJECT",
    "K_LESSON_GENERATION_DECISIONS",
    "K_LESSON_GENERATION_DEFAULT_REVIEWER",
    "K_LESSON_GENERATION_NODE_PREPARE",
    "K_LESSON_GENERATION_NODE_AUTHOR",
    "K_LESSON_GENERATION_NODE_REVIEW",
    "K_LESSON_GENERATION_NODE_NORMALIZE",
    "K_LESSON_GENERATION_NODE_PRESERVATION",
    "K_LESSON_GENERATION_NODE_INTENT_REVIEW",
    "K_LESSON_GENERATION_NODE_EXERCISE_AUTHOR",
    "K_LESSON_GENERATION_NODE_EXERCISE_COMPILE",
    "K_LESSON_GENERATION_NODE_EXERCISE_VERIFY",
    "K_LESSON_GENERATION_NODE_COVERAGE",
    "K_LESSON_GENERATION_NODE_VERIFY_ATTESTATIONS",
    "K_LESSON_GENERATION_NODE_HUMAN_GATE",
    "K_LESSON_GENERATION_NODE_FINALIZE",
    "K_LESSON_GENERATION_EXPORT_INDENT",
]
