"""Entry points: `load_lesson` reads one authored package; `load_lesson_source` loads authored text.

The operation parses ``lesson.md`` and ``exercises.yaml``, constructs the final
``Lesson`` while walking the parsed source, and validates section roles,
exercise handles, declared objectives, and the recap anchor. Format mechanics
stay in ``formats/`` and focused application converters; construction state is
private to this module. Loading is deterministic: the same source yields
identical lessons, warnings, errors, identifiers, and generated bytes (no
``uuid4`` anywhere).
"""

from __future__ import annotations

import re
import uuid
from pathlib import Path
from typing import Any

import panflute

from lesson_builder.application.operations.convert_lesson_blocks import convert_blocks
from lesson_builder.application.operations.convert_lesson_spans import convert_inlines
from lesson_builder.application.operations.convert_lesson_spans import stringify_inlines
from lesson_builder.application.operations.load_exercises import load_exercises
from lesson_builder.domain.lesson.models.elements import Exercise
from lesson_builder.domain.lesson.models.inline import InlineSpan
from lesson_builder.domain.lesson.models.inline import TextSpan
from lesson_builder.domain.lesson.models.lesson import Lesson
from lesson_builder.domain.lesson.models.source_audit import MechanicalAudit
from lesson_builder.formats.markdown.frontmatter import FrontmatterObjective
from lesson_builder.formats.markdown.frontmatter import parse_frontmatter
from lesson_builder.formats.markdown.frontmatter import parse_source_frontmatter
from lesson_builder.formats.markdown.pandoc import parse_markdown
from lesson_builder.formats.yaml import load_unique_yaml

K_LOAD_LESSON_FILE = "lesson.md"
K_LOAD_EXERCISES_FILE = "exercises.yaml"

K_LOAD_SECTION_ROLES: tuple[str, ...] = ("orient", "model", "contrast", "recap")

# A full exercise marker paragraph: {{exercise: handle}} on its own.
K_LOAD_EXERCISE_RE = re.compile(r"^\{\{exercise:\s*([^}\s]+)\}\}$")

# Detect any partial/inline exercise marker (to reject it).
K_LOAD_EXERCISE_PARTIAL_RE = re.compile(r"\{\{exercise:")

K_LOAD_SNIPPET_LIMIT = 80

K_LOAD_IDENTITY_NAMESPACE = uuid.UUID("7e3a2b48-9c1d-4f6a-b8e2-5d4c3b2a1f0e")
K_LOAD_IDENTITY_SEPARATOR = "|"
K_LOAD_CARD_ID_PREFIX = "card"


def load_lesson(
    source_dir: Path,
    *,
    audit: MechanicalAudit | None = None,
) -> Lesson:
    """Read one authored package and return its validated Lesson.

    When the caller already audited these source bytes, material findings stop
    loading before the package is read.
    """
    _require_optional_audit_pass(audit)
    root = Path(source_dir)
    return load_lesson_source(
        (root / K_LOAD_LESSON_FILE).read_text(encoding="utf-8"),
        (root / K_LOAD_EXERCISES_FILE).read_text(encoding="utf-8"),
    )


def load_plan_metadata(plan_path: Path) -> dict[str, Any]:
    """Read raw YAML metadata from one authored plan file."""
    return load_plan_metadata_source(Path(plan_path).read_text(encoding="utf-8"))


def load_plan_metadata_source(plan_text: str) -> dict[str, Any]:
    """Parse raw YAML metadata from captured authored plan text."""
    metadata, _ = parse_source_frontmatter(plan_text)
    return metadata


def load_lesson_source(
    lesson_text: str,
    exercises_text: str,
    *,
    audit: MechanicalAudit | None = None,
) -> Lesson:
    """Load authored Markdown and exercise YAML text into one validated Lesson."""
    _require_optional_audit_pass(audit)
    frontmatter, body = parse_frontmatter(lesson_text)
    warnings: list[str] = []
    exercises_list = load_exercises(exercises_text, warnings=warnings)
    exercise_by_handle = _exercise_map(exercises_text, exercises_list)
    declared_objective_ids = {objective.id for objective in frontmatter.objectives}

    elements: list[dict[str, Any]] = []
    exercise_record: list[tuple[str, str]] = []
    current_section: dict[str, Any] | None = None
    has_recap = False

    for element in parse_markdown(body).content:
        if isinstance(element, panflute.Header):
            current_section = _section_from_heading(
                element,
                warnings,
                frontmatter.default_lang,
            )
            elements.append(current_section)
            has_recap = has_recap or current_section["role"] == "recap"
            continue

        if isinstance(element, panflute.Para):
            handle = _exercise_marker(element)
            if handle is not None:
                current_section = None
                exercise = _require_exercise(exercise_by_handle, handle)
                _require_known_objective(
                    exercise.objective_id,
                    declared_objective_ids,
                    handle,
                )
                elements.append(exercise.model_dump(mode="json"))
                exercise_record.append((exercise.objective_id, exercise.id))
                continue

        block = convert_blocks([element], warnings, frontmatter.default_lang)[0]
        if current_section is not None:
            current_section["blocks"].append(block.model_dump(mode="json"))

    if not has_recap:
        raise ValueError(
            "missing recap section — every lesson requires a '## recap: ...' "
            "section in lesson.md. Fix: add a recap section to lesson.md."
        )

    lesson_data: dict[str, Any] = {
        "key": frontmatter.slug,
        "concept_slug": frontmatter.slug,
        "grounding_mode": frontmatter.grounding_mode,
        "title": frontmatter.title,
        "cefr_level": frontmatter.cefr_level,
        "goal": frontmatter.goal,
        "objectives": [objective.model_dump(mode="json") for objective in frontmatter.objectives],
        "elements": elements,
        "review_pool": _review_pool(frontmatter.objectives, exercise_record, frontmatter.slug),
    }

    try:
        return Lesson.model_validate(lesson_data)
    except Exception as exc:
        raise ValueError(f"loaded lesson failed Lesson.model_validate: {exc}") from exc


def _require_audit_pass(audit: MechanicalAudit) -> None:
    """Raise with the existing source evidence when material findings remain."""
    if not audit.material_findings:
        return
    details = "; ".join(
        f"{finding.code}@{finding.location} ({finding.severity}): {finding.explanation} Evidence: {finding.evidence}"
        for finding in audit.material_findings
    )
    raise ValueError(f"mechanical exercise preflight blocked lesson loading: {details}")


def _require_optional_audit_pass(audit: MechanicalAudit | None) -> None:
    """Require a supplied audit to pass before loading source text."""
    if audit is not None:
        _require_audit_pass(audit)


def _section_from_heading(
    el: panflute.Header,
    warnings: list[str],
    default_lang: str,
) -> dict[str, Any]:
    """Create a final lesson section from a Pandoc heading.

    Reads role from the explicit ``role=`` attribute or the legacy
    heading-text prefix, id from ``el.identifier``, objective_ids from
    ``el.attributes['objectives']``, and title from the learner-facing heading
    text. Explicit role metadata keeps internal section roles out of the title.
    """
    spans = convert_inlines(el.content, warnings, default_lang)
    prefixed_role, prefixed_title_spans = _role_and_title(spans)
    role_attribute = el.attributes.get("role")
    if role_attribute is not None:
        role = role_attribute.strip()
        if role not in K_LOAD_SECTION_ROLES:
            raise ValueError(
                f"heading role attribute must be one of "
                f"{', '.join(K_LOAD_SECTION_ROLES)}, got {role!r}. "
                f"Snippet: {_spans_to_text(spans)[:K_LOAD_SNIPPET_LIMIT]}"
            )
        if prefixed_role is not None and prefixed_role != role:
            raise ValueError(
                f"heading role attribute {role!r} conflicts with prefix "
                f"{prefixed_role!r}. Remove the visible prefix and keep role=... "
                f"as the source metadata. "
                f"Snippet: {_spans_to_text(spans)[:K_LOAD_SNIPPET_LIMIT]}"
            )
        title_spans = spans if prefixed_role is None else prefixed_title_spans
    else:
        role = prefixed_role
        title_spans = prefixed_title_spans
    if role is None:
        text = _spans_to_text(spans)
        raise ValueError(
            f"heading must declare a section role with role=... or the legacy "
            f"section-role prefix (orient:, model:, contrast:, recap:). "
            f"Snippet: {text[:K_LOAD_SNIPPET_LIMIT]}"
        )

    section_id = el.identifier
    if not section_id:
        text = _spans_to_text(spans)
        raise ValueError(
            f"heading must have an explicit id attribute "
            f"(e.g. '{{#sec-intro}}'). "
            f"Snippet: {text[:K_LOAD_SNIPPET_LIMIT]}"
        )

    objectives_raw = el.attributes.get("objectives", "")
    objective_ids = [s.strip() for s in objectives_raw.split(",") if s.strip()]

    return {
        "element_kind": "section",
        "id": section_id,
        "role": role,
        "objective_ids": objective_ids,
        "title": _spans_to_text(title_spans),
        "blocks": [],
    }


def _role_and_title(spans: list[InlineSpan]) -> tuple[str | None, list[InlineSpan]]:
    """Extract the section-role prefix from heading spans.

    Returns ``(role, remaining_spans)``. If no role prefix is found, returns
    ``(None, spans)``.
    """
    if not spans:
        return None, spans
    first = spans[0]
    text = getattr(first, "value", None)
    if text is None:
        return None, spans
    for role in K_LOAD_SECTION_ROLES:
        prefix = role + ":"
        if text == prefix:
            remaining = spans[1:] if len(spans) > 1 else []
            return role, remaining
        if text.startswith(prefix + " "):
            new_text = text[len(prefix) + 1 :]
            new_spans = list(spans)
            if new_text:
                new_spans[0] = TextSpan(kind="text", value=new_text)
            else:
                new_spans = new_spans[1:]
            return role, new_spans
    return None, spans


def _exercise_marker(el: panflute.Para) -> str | None:
    """Check if a paragraph is a full ``{{exercise: handle}}`` marker.

    Returns the handle if the paragraph text is exactly an exercise marker.
    Raises ``ValueError`` for partial/inline markers. Returns ``None`` for
    paragraphs that do not contain the marker pattern at all.
    """
    text = stringify_inlines(el.content).strip()
    match = K_LOAD_EXERCISE_RE.match(text)
    if match:
        return match.group(1)
    if K_LOAD_EXERCISE_PARTIAL_RE.search(text):
        raise ValueError(
            f"exercise marker must be on its own line as "
            f"'{{{{exercise: handle}}}}'. "
            f"Found inline/partial marker in: {text[:K_LOAD_SNIPPET_LIMIT]}"
        )
    return None


def _exercise_map(yaml_text: str, exercises: list[Exercise]) -> dict[str, Exercise]:
    """Build a ``handle → Exercise`` map from the YAML text and loaded exercises."""
    raw_items = load_unique_yaml(yaml_text)
    if raw_items is None:
        raw_items = []
    if not isinstance(raw_items, list):
        raise ValueError("exercises.yaml must be a YAML list of exercise mappings.")  # noqa: TRY004 (historical ValueError contract)

    if len(raw_items) != len(exercises):
        raise ValueError(
            f"exercises.yaml item count ({len(raw_items)}) does not match loaded exercises ({len(exercises)})."
        )

    result: dict[str, Exercise] = {}
    for raw_item, exercise in zip(raw_items, exercises, strict=True):
        if not isinstance(raw_item, dict):
            raise ValueError("each exercises.yaml item must be a mapping.")  # noqa: TRY004 (historical ValueError contract)
        handle = raw_item.get("handle")
        if not isinstance(handle, str):
            raise ValueError("each exercises.yaml item must have a string 'handle'.")  # noqa: TRY004 (historical ValueError contract)
        if handle in result:
            raise ValueError(f"duplicate exercises.yaml handle {handle!r}.")
        result[handle] = exercise
    return result


def _spans_to_text(spans: list[InlineSpan]) -> str:
    """Flatten internal spans into a plain text string."""
    parts: list[str] = []
    for span in spans:
        value = getattr(span, "value", None)
        if value is not None:
            parts.append(value)
        elif getattr(span, "kind", None) == "sentence":
            children = getattr(span, "children", [])
            parts.append(_spans_to_text(children))
    return "".join(parts)


def _review_pool(
    objectives: list[FrontmatterObjective],
    exercise_record: list[tuple[str, str]],
    slug: str,
) -> dict[str, Any]:
    """Build one review pool per objective with source-derived card UUIDs."""
    pools: list[dict[str, Any]] = []
    for objective in objectives:
        pool_key = objective.id
        # Exercises for this objective, in document order.
        pool_exercise_ids = [exercise_id for objective_id, exercise_id in exercise_record if objective_id == pool_key]
        cards: list[dict[str, Any]] = []
        for ordinal, exercise_id in enumerate(pool_exercise_ids):
            card_uuid = str(
                uuid.uuid5(
                    K_LOAD_IDENTITY_NAMESPACE,
                    K_LOAD_IDENTITY_SEPARATOR.join([slug, K_LOAD_CARD_ID_PREFIX, pool_key, exercise_id, str(ordinal)]),
                )
            )
            cards.append({"uuid": card_uuid, "exercise_id": exercise_id})
        pools.append(
            {
                "key": pool_key,
                "objective_id": pool_key,
                "cards": cards,
            }
        )
    return {"pools": pools}


def _require_exercise(exercises: dict[str, Exercise], handle: str) -> Exercise:
    """Return the exercise for a source marker or raise with a repair hint."""
    try:
        return exercises[handle]
    except KeyError as exc:
        raise ValueError(
            f"exercise handle {handle!r} not found in exercises.yaml. "
            f"Fix: add an exercise with handle {handle!r} or fix the "
            f"marker in lesson.md."
        ) from exc


def _require_known_objective(exercise_objective: str, declared: set[str], handle: str) -> None:
    """Raise if an exercise references an undeclared objective."""
    if exercise_objective not in declared:
        raise ValueError(
            f"exercise {handle!r} references objective {exercise_objective!r} "
            f"which is not declared in frontmatter objectives {sorted(declared)}."
        )


__all__ = [
    "load_lesson",
    "load_plan_metadata",
    "load_lesson_source",
]
